config/routes.rb
Rails.application.routes.draw do
  root "posts#index"
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  
  resources :posts do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments
  
  validates :title, presence: true
  validates :description, presence: true, length: { minimum: 10 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password)}
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    redirect_to post_path(@post)
  end

  private

  def comment_params
    params.require(:comment).permit(:description).merge(commenter: current_user&.name)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: %i[show edit update destroy]

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to posts_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit;end

  def update
    if @post.update(post_params)
      redirect_to posts_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @post.destroy

    redirect_to root_path, status: :see_other
  end

  private

  def post_params
    params.require(:post).permit(:title, :description).merge(user: current_user)
  end

  def find_post
    @post = Post.find_by(id: params[:id])
    unless @post.present?
      redirect_to root_path
      flash[:notice] = "Something went wrong"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div>
  <strong><%= comment.commenter %></strong>
</div>
<div>
  <%= comment.description %>
</div>

app/views/comments/_form.html.erb
<%= form_with model: [ @post, @post.comments.build ], class: "send-message-form" do |form| %>
  <div class="row">
    <div class="col-11">
      <%= form.text_field :description, class:"form-control  col-md-3 mr-1", placeholder: "Add Comments..." %>
    </div>
    <div class="col-1 text-end">   
      <%= form.button '<i class="bi bi-send-fill"></i>'.html_safe, type: 'submit', data: {disable_with: false}, class: 'btn btn-light' %>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with model: post do |form| %>
  <div class="mt-4">
    <%= form.label :title %>
    <%= form.text_field :title, class:"form-control  col-md-3 mr-1"%>
    <% post.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div class="mt-4">
    <%= form.label :description %>
    <%= form.text_area :description, class:"form-control  col-md-3 mr-1" %>
    <% post.errors.full_messages_for(:description).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div class="mt-4">
    <%= form.submit class:"btn btn-lg btn-primary btn-block form-control col-md-3 mr-1" %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div class="row">
  <div class="col-sm-9 col-md-7 col-lg-4 mx-auto">
    <div class="card my-5 shadow">
      <div class="card-body m-3">
        <div class="row">
          <div class="col">
            <h2>Edit Post</h2>
          </div>

          <div class="col-md-1 text-right">
            <%= link_to root_path, class: "btn btn-primary", toggle: 'tooltip', placement: 'top', title: 'Back' do %>
              <i class='bi bi-arrow-left' aria-hidden='true'></i>
            <% end %>
          </div>
          <%= render 'form', post: @post %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-11 d-flex justify-content-center align-items-center ">
      <h2>Posts</h2>
    </div>
    <div class="col text-end mt-4">
      <%= link_to new_post_path, class:"btn btn-light " do %>
        <i class="bi bi-plus-circle-fill"></i>
      <% end %>
    </div>
  </div>

  <% @posts.each do |post| %>
    <div class="card mt-4 mb-4">
      <div class="card-header">
        <%= post.user&.name %>
        <div class="float-end">
        <%= link_to post_path(post), class:"btn btn-light " do %>
          <i class="bi bi-chat-right-text-fill"></i>
         <% end %> 
        </div>
      </div>
      <div class="card-body text-center">
        <h5 class="card-title">
          <%= post.title %>
        </h5>
        <p class="card-text">
          <%= post&.description%>
        </p>
        <%= link_to edit_post_path(post), class: "btn btn-light" do %>
          <i class="bi bi-pencil-fill"></i>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<div class="row">
  <div class="col-sm-9 col-md-7 col-lg-4 mx-auto">
    <div class="card my-5 shadow">
      <div class="card-body m-3">
        <div class="row">
          <div class="col">
            <h2>Create Post</h2>
          </div>

          <div class="col-md-1 text-right">
            <%= link_to root_path, class: "btn btn-primary", toggle: 'tooltip', placement: 'top', title: 'Back' do %>
              <i class='bi bi-arrow-left' aria-hidden='true'></i>
            <% end %>
          </div>
          <%= render 'form', post: @post%>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="container mt-4">
  <div class="card text-center mt-2">
    <div class="card-header">
      Comments
    </div>
  </div>
  <div class="chat-container">
    <div class="message">
      <%= render @post.comments %>
    </div>
  </div>
  <%= render 'comments/form' %>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar sticky-top bg-light">
  <div class="container-fluid">
    <%= link_to "Test App", root_path, class: "navbar-brand" %>
    <% if user_signed_in? %>
      <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "float-end nav-link" %>
    <% end %>
  </div>
</nav>